name: Changelog check
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

env:
  NODE_VERSION: 20.x

jobs:
  towncrier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history
          fetch-depth: '0'

      - name: Install towncrier
        run: pip install towncrier

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable corepack
        run: corepack enable

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: make install

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            blocks:
              - 'packages/volto-blocks/**'
            slateExtras:
              - 'packages/volto-slate-extras/**'

      - name: volto-blocks changelog check
        if: steps.filter.outputs.blocks == 'true'
        run: |
          # Fetch the pull request' base branch so towncrier will be able to
          # compare the current branch with the base branch.
          # Source: https://github.com/actions/checkout/#fetch-all-branches.
          git fetch --no-tags origin ${BASE_BRANCH}
          towncrier check --compare-with origin/${BASE_BRANCH} --dir packages/volto-blocks
        env:
          BASE_BRANCH: ${{ github.base_ref }}

      - name: volto-slate-extras changelog check
        if: steps.filter.outputs.slateExtras == 'true'
        run: |
          git fetch --no-tags origin ${BASE_BRANCH}
          towncrier check --compare-with origin/${BASE_BRANCH} --dir packages/volto-slate-extras
        env:
          BASE_BRANCH: ${{ github.base_ref }}
