name: Release latest version on npm

on:
  release:
    types: [released]

jobs:
  release_to_npm:
    name: Release to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g npm

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Release to npm
        run: npm publish --provenance --access public
        working-directory: packages/volto-blocks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
