name: Release latest version on npm

on:
  release:
    types: [released]

env:
  NODE_VERSION: 20.x

jobs:
  release_to_npm:
    name: Release to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g npm

      - name: Enable corepack
        run: corepack enable

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: make install

      - name: Extract package from release tag
        id: get_package
        run: |
          RELEASE_TAG=${GITHUB_REF/refs\/tags\//}
          echo "PACKAGE=$(echo $RELEASE_TAG | cut -d'@' -f1)" >> $GITHUB_OUTPUT

      - name: Release to npm
        run: npm publish --provenance --access public
        working-directory: ./packages/${{ steps.get_package.outputs.PACKAGE }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
